theme: jekyll-theme-minimal
title: Beat Box
description: A novel song recommendatoin system built using Content Based Filtering and Natural Language Processing by Ansh Sachdeva and Shivam Vats
logo: /assets/img/logo.png
